### ISSUE TITLE
usbagb open then quickly closes

### ISSUE THREAD

**Issue by 112RG** [Twilight/uCAGB#1]
I compiled usbagb but when I open it it quickly closes do you have a compiled version I could try?

**Comment by 112RG** [comment]
I found that it needs to be run by command prompt but how do I find out what the serial devices name is??

**Comment by Jimmy-Z** [comment]
Use device manager or google "windows serial device name"

**Comment by 112RG** [comment]
Leonardo Arduino-Compatible Pro Micro ATmega32U4 This will work right?

**Comment by Jimmy-Z** [comment]
yeah it should work
