### ISSUE TITLE
White screen 

### ISSUE THREAD

**Issue by 112RG** [Twilight/uCAGB#2]
When I try and send a rom it shows a white screen your dfagb works but every other I try is white I am trying this http://www.coranac.com/tonc/text/first.htm

**Comment by Jimmy-Z** [comment]
1, it must be a multiboot ROM.
2, the header must be fixed.
3, Just like you've said, dfagb works, so obviously this tool set is working fine, I think you should ask somewhere else like devkitpro forum instead?

**Comment by 112RG** [comment]
adding _mb worked thank you 👍

**Comment by Jimmy-Z** [comment]
Glad to help :)
